### ISSUE TITLE
Block Directory Implementation Checklist

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/block-library#21]
This is an implementation task list for the block directory.

## wp-admin

- [ ] [Implement new page header](https://core.trac.wordpress.org/ticket/51751#ticket)
- [ ] [Implement block cards](https://github.com/WordPress/block-directory/issues/22)
- [ ] [Create demo editor](https://github.com/WordPress/block-directory/issues/23)
- [ ] Add demo to existing block detail pages
- [ ] Implement the block detail design

## WordPress.org

- [ ] [Implement image generator](https://github.com/WordPress/block-directory/issues/20)
- [ ] [Implement block cards](https://github.com/WordPress/block-directory/issues/22)
- [ ] [Create demo editor](https://github.com/WordPress/block-directory/issues/23)
- [ ] Add demo to existing block detail pages
- [ ] Implement the block detail design
